# Generated by Django 5.2.4 on 2025-07-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_jobpost_reference_number_alter_jobpost_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
